apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nkp-clusters-automation
  namespace: kommander
spec:
  dependsOn:
  - name: nkp-auto-workspaces
    namespace: kommander
  interval: 5s
  path: ./kustomizations/clusters
  prune: true
  sourceRef:
   kind: GitRepository
   name: nkp-wolves-automation
   namespace: kommander
