apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: clusterops-clusters
  namespace: kommander
spec:
  dependsOn:
  - name: clusterops-workspaces
    namespace: kommander
  interval: 5s
  path: ./kustomizations/clusters
  prune: true
  sourceRef:
   kind: GitRepository
   name: gitops-demo
   namespace: kommander
