apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nkp-kustomization
  namespace: kommander
spec:
  dependsOn:
  - name: clusterops-workspaces
    namespace: kommander
  interval: 5s
  path: ./kustomizations/projects
  prune: true
  sourceRef:
   kind: GitRepository
   name: nkp-automation
   namespace: kommander
