apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nkp-workspaces-automation
  namespace: kommander
spec:
  interval: 5s
  path: ./kustomizations/workspaces
  prune: true
  sourceRef:
   kind: GitRepository
   name: nkp-wolves-automation
   namespace: kommander
