apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nkp-kustomization
  namespace: kommander
spec:
  interval: 5s
  path: ./kustomizations/workspaces
  prune: true
  sourceRef:
   kind: GitRepository
   name: nkp-automation
   namespace: kommander
