apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nkp-apps-automation
  namespace: kommander
spec:
  dependsOn:
  - name: nkp-workspaces-automation
    namespace: kommander
  interval: 5s
  path: ./kustomizations/workspaces/applications
  prune: true
  sourceRef:
   kind: GitRepository
   name: nkp-wolves-automation
   namespace: kommander
