apiVersion: workspaces.kommander.mesosphere.io/v1alpha1
kind: VirtualGroupWorkspaceRoleBinding
metadata:
  finalizers:
  - workspaces.kommander.mesosphere.io/virtualgroupworkspacerolebinding
  namespace: wolves
  name: wolves-workspace-admin
spec:
  placement:
    clusterSelector: {}
  virtualGroupRef:
    name: workspace-admin
  workspaceRoleRef:
    name: workspace-admin
