apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: signarf
    konvoy.d2iq.io/provider: nutanix
  name: signarf
  namespace: wolves
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: ""
    port: 0
  topology:
    class: nkp-nutanix
    controlPlane:
      metadata: {}
      replicas: 1
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: signarf-pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          cosi:
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: signarf-pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: true
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for signarf
                      flashMode: DISABLED
                      hypervisorAttached: ENABLED
                      storageContainer: GSO-Everglade-07-StorageContainer
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - end: 10.48.104.112
                start: 10.48.104.112
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: GSO-Everglade-07
                type: name
              image:
                name: nkp-rocky-9.5-release-1.30.5-20241125163629.qcow2
                type: name
              memorySize: 8Gi
              subnets:
              - name: "567"
                type: name
              systemDiskSize: 80Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        dns:
          coreDNS: {}
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          url: http://10.48.104.168:5000
        nutanix:
          controlPlaneEndpoint:
            host: 10.48.104.111
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: signarf-pc-credentials
            insecure: true
            url: https://10.48.53.237:9440
        users:
        - name: konvoy
          sshAuthorizedKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCslABnAjxzsUjIGRVpb5BVmX0PNIhyJSdix53+sEq6yILP6iUz1nGuW2aedv8IEyLl
JNA+UIOA8k0x3yVk50PdYmBjB99+szSeMIKknVNsnzEB0BjaBrrc31IilqiNe4o0OivM0Jlq7hTEUOA8/1JB2CBb8ddymYEQjBmZa21hQVZHyI2xaYsE
6pLGZzFZJaN8iWeF9cioZFxwN1ONbAT67Sg5vNJygKu+8sCwBtZEdBsHN+mas6zA7zVpzAF/X2HWJKJGecCJpoucKuILdxC853OrRBBfrVWTjvzS3Iuo
1Ow+zrwRSWH7BE4IWOnB4SNxjPRw9oodO3GMvZmr8ak/LVFlFd82sdHc3O/F2yr3RG8ORoqjxY3vnpNDQlFV6zLtxS05PICl+FWBFnl+/7sK6FLAlj2p
H0zPhJK+QX6U2KIKIgxjSwNeoJ4O6K48agWVToO0MCKLCXt42rVkLvGtII7GeHgLhNIkeXfNw6nThVq6iIlHGHZFJ3I7MZYbtH0=
          sudo: ALL=(ALL) NOPASSWD:ALL
    version: v1.31.4
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "1"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
        name: md-0
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: GSO-Everglade-07
                    type: name
                  image:
                    name: nkp-rocky-9.5-release-1.30.5-20241125163629.qcow2
                    type: name
                  memorySize: 24Gi
                  subnets:
                  - name: "567"
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1
---
apiVersion: v1
data:
  credentials: WwogICAgewogICAgICAgICJ0eXBlIjogImJhc2ljX2F1dGgiLAogICAgICAgICJkYXRhIjogewogICAgICAgICAgICAicHJpc21DZ
W50cmFsIjogewogICAgICAgICAgICAgICAgInVzZXJuYW1lIjogImFkbWluIiwKICAgICAgICAgICAgICAgICJwYXNzd29yZCI6ICJQZXBwb2xpJDIwM
jAiCiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9Cl0=
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: signarf
    konvoy.d2iq.io/provider: nutanix
  name: signarf-pc-credentials
  namespace: wolves
type: Opaque
---
apiVersion: v1
data:
  key: MTAuNDguNTMuMjM3Ojk0NDA6YWRtaW46UGVwcG9saSQyMDIw
kind: Secret
metadata:
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: signarf
    konvoy.d2iq.io/provider: nutanix
  name: signarf-pc-credentials-for-csi
  namespace: wolves
type: Opaque
