apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: matriarch
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: matriarch
    konvoy.d2iq.io/provider: nutanix
    topology.cluster.x-k8s.io/owned: ""
  name: matriarch
  namespace: wolves
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneEndpoint:
    host: "10.48.104.177"
    port: 6443
  topology:
    class: nkp-nutanix
    controlPlane:
      metadata: {}
      replicas: 3
    variables:
    - name: clusterConfig
      value:
        addons:
          ccm:
            credentials:
              secretRef:
                name: pc-credentials
            strategy: HelmAddon
          clusterAutoscaler:
            strategy: HelmAddon
          cni:
            provider: Cilium
            strategy: HelmAddon
          csi:
            defaultStorage:
              provider: nutanix
              storageClassConfig: volume
            providers:
              nutanix:
                credentials:
                  secretRef:
                    name: pc-credentials-for-csi
                storageClassConfigs:
                  volume:
                    allowExpansion: false
                    parameters:
                      csi.storage.k8s.io/fstype: ext4
                      description: CSI StorageClass nutanix-volume for matriarch
                      flashMode: DISABLED
                      hypervisorAttached: ENABLED
                      storageContainer: default
                      storageType: NutanixVolumes
                    reclaimPolicy: Delete
                    volumeBindingMode: WaitForFirstConsumer
                strategy: HelmAddon
            snapshotController:
              strategy: HelmAddon
          nfd:
            strategy: HelmAddon
          serviceLoadBalancer:
            configuration:
              addressRanges:
              - start: 172.16.0.17
                end: 172.16.0.19
            provider: MetalLB
        controlPlane:
          nutanix:
            machineDetails:
              bootType: uefi
              cluster:
                name: matriarch
                type: name
              image:
                name: nkp-rocky-9.5-1.31.4-20250317202029
                type: name
              memorySize: 16Gi
              project:
                name: nkp-lab
                type: name
              subnets:
              - name: 567
                type: name
              systemDiskSize: 80Gi
              vcpuSockets: 4
              vcpusPerSocket: 1
        encryptionAtRest:
          providers:
          - secretbox: {}
        globalImageRegistryMirror:
          credentials:
            secretRef:
              name: image-registry-mirror-credentials
          url: https://harbor.infrastructure.cloudnative.nvdlab.net/nkp
        nutanix:
          controlPlaneEndpoint:
            host: 172.16.0.15
            port: 6443
            virtualIP:
              provider: KubeVIP
          prismCentralEndpoint:
            credentials:
              secretRef:
                name: pc-credentials
            insecure: false
            url: https://pc.dragon.cloudnative.nvdlab.net:9440
        users:
        - name: bovan01
          sshAuthorizedKeys:
          - |
            ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCslABnAjxzsUjIGRVpb5BVmX0PNIhyJSdix53+sEq6yILP6iUz1nGuW2aedv8IEyLlJNA+UIOA8k0x3yVk50PdYmBjB99+szSeMIKknVNsnzEB0BjaBrrc31IilqiNe4o0OivM0Jlq7hTEUOA8/1JB2CBb8ddymYEQjBmZa21hQVZHyI2xaYsE6pLGZzFZJaN8iWeF9cioZFxwN1ONbAT67Sg5vNJygKu+8sCwBtZEdBsHN+mas6zA7zVpzAF/X2HWJKJGecCJpoucKuILdxC853OrRBBfrVWTjvzS3Iuo1Ow+zrwRSWH7BE4IWOnB4SNxjPRw9oodO3GMvZmr8ak/LVFlFd82sdHc3O/F2yr3RG8ORoqjxY3vnpNDQlFV6zLtxS05PICl+FWBFnl+/7sK6FLAlj2pH0zPhJK+QX6U2KIKIgxjSwNeoJ4O6K48agWVToO0MCKLCXt42rVkLvGtII7GeHgLhNIkeXfNw6nThVq6iIlHGHZFJ3I7MZYbtH0=
          sudo: ALL=(ALL) NOPASSWD:ALL
    version: v1.31.4
