apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  annotations:
    caren.nutanix.com/cluster-uuid: 0192decb-8f55-75f3-a356-be154916a399
    kustomize.toolkit.fluxcd.io/ssa: merge
    kustomize.toolkit.fluxcd.io/prune: disabled    
  labels:
    cluster.x-k8s.io/provider: nutanix
    konvoy.d2iq.io/cluster-name: nkp-dragon-wld-1
    konvoy.d2iq.io/provider: nutanix
  name: nkp-dragon-wld-1
  namespace: batcave
spec:
  topology:
    workers:
      machineDeployments:
      - class: default-worker
        metadata:
          annotations:
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "1"
            cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "1"
        name: pool2
        variables:
          overrides:
          - name: workerConfig
            value:
              nutanix:
                machineDetails:
                  bootType: uefi
                  cluster:
                    name: dragon
                    type: name
                  image:
                    name: nkp-ubuntu-22.04-1.29.6-20240905041334
                    type: name
                  memorySize: 32Gi
                  project:
                    name: arvind-lab
                    type: name
                  subnets:
                  - name: ab-overlay
                    type: name
                  systemDiskSize: 80Gi
                  vcpuSockets: 8
                  vcpusPerSocket: 1  
