apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deploy-nkp-dragon-wld-1.yaml
patches:
 - target:
      group: cluster.x-k8s.io
      version: v1beta1
      kind: Cluster
      name: nkp-dragon-wld-1
   path: deploy-nkp-dragon-wld-1-pools.yaml